### ISSUE TITLE
Setting to repeat the Cookie Info

### ISSUE THREAD

**Issue by dionysis777** [JoomBall/JBCookies#1]
Please is there a setting to repeat the Cookie Info after X days?!
Thank you

**Comment by JoomBall** [comment]
I will add this option in the next version for you at the beginning of July.
You will also have the possibility to delete cookies as you can see in the position of my template.

![delede_cookies](https://user-images.githubusercontent.com/16047586/40923362-f11bb5fe-6814-11e8-8ca7-b0e398f3e440.png)

**Comment by dionysis777** [comment]
Hi. Thank you for your answer!
If you will add this, it will be the perfect module for Cookies!!!

I will try to promote and comment for your module.
Best wishes,
Dionysis

-- 
Dionysis Vourtsis
Biomedical Laboratory Scientist, BSc, IFBA PC
ASCPi Europe Regional Representative
ASCPi Greek Advisory Board President 
IFBA Communications & Project Officer
IFBLS CD Member at Large
PETIE (Greek MLT Association) President
Greek National Primary Health Care System
Tel: +30 6977433301 
Skype: dionysis.vourtsis 
http://www.linkedin.com/pub/dionysis-vourtsis/47/106/147

**Comment by Tecommerce** [comment]
Hi, how can I add the "Eliminar cookies" link / button?
I don't find any option in the module settings.

Thank you!!

**Comment by JoomBall** [comment]
This option is in beta and you will have a stable update in the first week of July.

**Comment by Tecommerce** [comment]
Ok, thank you.
Waiting for this update!!

**Comment by JoomBall** [comment]
All the features added in the new version.

**Comment by dionysis777** [comment]
[image: 2025.jpg]

-- 
Dionysis Vourtsis
Biorisk Management Advisor, MSc, IFBA PC
Licensed Biosafety Officer by RIVM/VSP/Bureau GGO in the Netherlands for
BSL1-3 laboratories
IFBA Certified in Biorisk Management, Risk Assessment, Biocontainment,
Biosecurity, Cyberbiosecurity, Waste Management and Biosafety Cabinets
HBS (Hellenic Biosafety Society) - President
IFBA (International Federation of Biosafety Associations) - Communications
& Project Officer
EBSA (European Biosafety Association) - CPWG
ASCPi (American Society for Clinical Pathology international) - Europe
Regional Representative
Tel: +30 6977433301
http://www.linkedin.com/pub/dionysis-vourtsis/47/106/147
<https://bitli.pro/2ke3X_d00af4b6>

--
Unsubscribe <https://bitli.pro/2ke3Y_0d100b4b>
