### ISSUE TITLE
Wrong URL when clicking Learn more

### ISSUE THREAD

**Issue by AJytzler** [JoomBall/JBCookies#10]
Hey guys. When clicking "Learn more" it opens a wrong URL for my cookie policy article. Any ideas?
Check it out here: http://liceng.dk/

**Comment by joboca** [comment]
It is a problem of url in Joomla, you have to create a menu for the article or a menu of the category of the article.

**Comment by AJytzler** [comment]
Thanks joboca. Will look into it.
