### ISSUE TITLE
Mobile display

### ISSUE THREAD

**Issue by mikebosher** [JoomBall/JBCookies#11]
Hi
The JB Cookies pop up works fine on my PC but links do not work on mobile

Thanks
Mike

**Comment by joboca** [comment]
Hi Mike,
I can not solve something that I can not see on your page.
Surely you are using another browser on the mobile.
Check any errors in the browser console.

**Comment by mikebosher** [comment]
Hi

 

Thanks for reply

 

Is now active on www.kimsshop.co.uk <http://www.kimsshop.co.uk> 

 

Mike

**Comment by joboca** [comment]
The problem is in some class of template that adds 'z-index' top layer.
You should verify all the css template.
For your understanding add,
.jb.cookie {z-index: 1050;}

Then try,
.jb.cookie {z-index: 9999;}

**Comment by mikebosher** [comment]
Hi

 

Excuse my ignorance where do I add code

 

Using a rocket theme template

 

Thanks

Mike

**Comment by joboca** [comment]
Sorry Mike, I do not use rocket theme.
Look for a field to add custom css.

**Comment by mikebosher** [comment]
Hi

 

.jb.cookie {z-index: 9999;}

 

Worked

 

Thanks

Mike

**Comment by joboca** [comment]
Surely you will need to visualize above the pop-up window.

#jbcookies {z-index: 9999;}
