### ISSUE TITLE
Styling no longer working?

### ISSUE THREAD

**Issue by webcoast** [JoomBall/JBCookies#13]
Hi, I just upgraded to Joomla 3.9.4 and noticed that the styling of the module has been lost. I'm not sure how long it has been like this, I just noticed. https://webcoast.com.au

Usually it is has black background and a blue button. These options are still set in the module, but don't appear on the site. It displays at the bottom of the page.

Thanks

**Comment by JoomBall** [comment]
Hace tiempo esto se resolvio actualizando, cualquier cosa vuelva a solicitar.
