### ISSUE TITLE
Features request add Background color

### ISSUE THREAD

**Issue by Milglius** [JoomBall/JBCookies#15]
Features request add Background color: Blue, Green, Orange, Red.

**Comment by JoomBall** [comment]
Hi @Milglius , you can now update version 3.1.5 with 3 updated parts as the image shows. How it is displayed depends mainly on your template.

![new_3 1 5](https://user-images.githubusercontent.com/16047586/77311619-c0c84780-6d00-11ea-83d1-aee02c206293.png)
