### ISSUE TITLE
Incorrect domain for cookie on the confirmation process

### ISSUE THREAD

**Issue by comproperty247** [JoomBall/JBCookies#17]
Hi,

I have a site with a subfolder for developing and testing before implement them alive.
The cookie was not always written and seems is because my "dev site" is in a subfolder!
Was something like for example "foo.com/dev" and the domain result was "foo.comdev"

In your file mod_jbcookies.php is this:
$domain = str_replace(array('https://www.', 'http://www.', 'https://', 'http://'), '', JUri::base());

I replaced with something more simpler:
$domain = $_SERVER['SERVER_NAME'];

And is working for me! The version I'm using is 3.1.4
Please test it, not sure if some servers return this variable as empty, but perhaps with a IF condition can solve this issue in sites working in sub folders.

Regards,
Carlos

**Comment by JoomBall** [comment]
First update to the latest version 3.1.6, this will work for you.

![Update](https://user-images.githubusercontent.com/16047586/80567731-137ada80-89f6-11ea-9190-279808b115d6.png)

At the request of a person, a parameter was added to use the same cookie in domain aliases.
Keep the 'Show same subdomain' option set to NO and it will work for you.
In YES, it is used for domains type: domain.com, alias.domain.com

![Parameters](https://user-images.githubusercontent.com/16047586/80567818-28f00480-89f6-11ea-8a86-c9e176b9c1e9.png)

**Comment by comproperty247** [comment]
Thanks, the issue is solved with last version 3.1.6
Regards
