### ISSUE TITLE
Please provide information what are these 2-3 bugs fixes in mod_jbcookies_3.1.6?

### ISSUE THREAD

**Issue by Milglius** [JoomBall/JBCookies#18]
Please provide information what are these 2-3 bugs fixes in mod_jbcookies_3.1.6? What was fixed  there? :)

thank you

**Comment by JoomBall** [comment]
Main problem has been the one mentioned in issue #17
Another problem may happen with the cache, for this a parameter has been created where accepting the cookie deletes the folders added in the field 'Clear cache'
