### ISSUE TITLE
Color and link to an artccle

### ISSUE THREAD

**Issue by alaincharles** [JoomBall/JBCookies#2]
Good afternoon,
My message concerns : www.v2.chaussonniere-ribeiro.fr
I used the release 3.0.8
I would like to use the option : "colors customized".
I selected the background color as black, but the message in the bottom appears as transparency
Regarding the link, the article does not appear rightly, the characters are transparency.
Thank you for your help,
Best regards,

**Comment by JoomBall** [comment]
It's true, there is a customizable template problem.
The next version will modify this option, probably at the beginning of July.
If you have time, you can collaborate in the French translation. Send to info@joomball.com

Thank you very much
[fr-FR.mod_jbcookies.zip](https://github.com/JoomBall/JBCookies/files/2098276/fr-FR.mod_jbcookies.zip)

**Comment by JoomBall** [comment]
Problem solved in the new version.
