### ISSUE TITLE
Expire Cookie

### ISSUE THREAD

**Issue by Pech184** [JoomBall/JBCookies#20]
Good Morning
I need to expire Cookie Banner but I can't in this new version.

[](https://www.kebabvalenza.com/alibaba/)

Everytime I click on Close Button ( ACCETTO in Italian ) next time banner come again

In Atachment, module option.... Maybe I must put the empty field but I don't know what...
Thanks
![joomball-issue](https://user-images.githubusercontent.com/68849577/88530808-38391b00-d002-11ea-8e52-9ba7a8fdbf09.jpg)

**Comment by JoomBall** [comment]
Hi @Pech184 ,

Your problem is explained in #17 , check this parameter 'Show same subdomain' in NO

Regards
