### ISSUE TITLE
Error CssIdentifier` missing

### ISSUE THREAD

**Issue by ssnobben** [JoomBall/JBCookies#24]
Hi 

tried this module again but didnt work with Joomla 3.10.3 php 8.0.12

Get this error after trying to save:

**An error has occurred.

    0 Joomla\CMS\Form\Form::validateField() rule `CssIdentifier` missing.** 

 
New version 4.0

**Comment by JoomBall** [comment]
The mod_jbcookies_4.0.0 version is only for Joomla 4, if you want to install the version for Joomla 3 use mod_jbcookies_3.1.9.

Once you decide to update Joomla 3 to 4, the new installation for Joomla 4 will appear.

Download manually in [https://github.com/JoomBall/JBCookies/releases](url)

**Comment by ssnobben** [comment]
ok thanks that was not clear in info there..

Cheers!

Obrigado
