### ISSUE TITLE
Issue with link to article Privacy policy

### ISSUE THREAD

**Issue by Alexa3083** [JoomBall/JBCookies#30]
Hi, I have a problem with the link "Read more" that should send to the privacy policy article.
It doesn't work. When you click on read more, nothing happens. When you move the cursor on the link, the path is www.mywebsite.it/#jbcookies , and it doesn't open the Privacy policy article (as set on the module, in language section).

I tried to update the module, but with the last version an error occur (I have joomla 3.9.26)

Please let me know how can I solve the problem
Thank you in advance

**Comment by tecnico10** [comment]
Anche io ho lo sesso problema se scelgo l'apertura con pop up.
Senza pop up è tutto a posto.
Cmq il pulsante declina non compare.

**Comment by Alexa3083** [comment]
Sì, il problema si manifesta con l'apertura pop up.
Pazienza, eviterò il pop up, però effettivamente rimane il problema del pulsante "declina" che non compare. Non ci sono soluzioni per questo problema?

**Comment by JoomBall** [comment]
For Joomla 3.x version you have to use mod_jbcookies_3.1.9

To open the article in the pop-up window depends on the template, for example you have to load some version of Bootstrap in the template and select it in the module parameters.

see more at #19
