### ISSUE TITLE
Uncaught ReferenceError: Squeezebox is not defined

### ISSUE THREAD

**Issue by gianmarcoodorizzi** [JoomBall/JBCookies#31]
Hello,
I get this error in my Console, I think it might be due to an incompatibility with my template?
The cookie bar is not showing up at all.
Do you have any suggestions?

flavioodorizzi. com

Thank you in advance

**Comment by JoomBall** [comment]
The template is not the problem, I use it a lot.

If you want to display cookie information in a popup window, select bootstrap 5 in the module.

If you have problems, unpublish the module to see if you still have the error in the console and look for the problem elsewhere.

**Comment by gianmarcoodorizzi** [comment]
Hello JoomBall and thank you for your message!
If I disable the module, the error disappears.
I am not sure what you mean with "select bootstrap 5", I cannot find such option. 
Using v. 3.1.9.

**Comment by gianmarcoodorizzi** [comment]
I found out what caused the module not to show up.
I have this extension installed: https://extensions.joomla.org/extension/mootools-enabler-disabler/ and it was set to disable both mootools and mootools-more. I solved by enabling both.
Is this expected?

Thank you

**Comment by JoomBall** [comment]
Hi @gianmarcoodorizzi 

It is not necessary to install anything, you can disable article in popup or select the correct option from its corresponding template

![Bootstrap 5](https://user-images.githubusercontent.com/16047586/175891632-d4ee0d35-bca8-42c0-ac3a-d54748c7b6ae.png)

**Comment by gianmarcoodorizzi** [comment]
Thank you for this, didn't see the option.
