### ISSUE TITLE
Will the module be updated?

### ISSUE THREAD

**Issue by kosh2323** [JoomBall/JBCookies#32]
A good module, is there an update planned? PHP 8.1. A warning pops up like this: "<b>Deprecated</b>:  htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in <b>SITE\modules\mod_jbcookies\mod_jbcookies.php</b> on line <b>62</b>"

**Comment by JoomBall** [comment]
Hi @kosh2323 

What version of jbcookies do you use?

In principle htmlspecialchars() is not deprecated in PHP 8

**Comment by kosh2323** [comment]
Hi, version 4.0.2, and PHP 8.1

**Comment by JoomBall** [comment]
Hi @kosh2323 ,

You can now update new version with the problem solved.

If it fails you, tell me something.

I close issue.

![Update_4 0 3](https://user-images.githubusercontent.com/16047586/190615066-f7b2e9b5-4c04-45d0-a7ce-9ca1fdd25492.png)

**Comment by kosh2323** [comment]
Thanks for the update.
