### ISSUE TITLE
Link to "Select an Article" not working?

### ISSUE THREAD

**Issue by saraheagle** [JoomBall/JBCookies#33]
Hello, I cannot seem to get the link to an article working it just does the #jbcookies link.
I have set it to show additional info & added the privacy article.

![Untitled-2](https://user-images.githubusercontent.com/8525279/195797451-61ca46de-eedb-495b-b37f-74960831407e.jpg)

Is this a bug, or am I missing something?
Thanks 
S :)

**Comment by JoomBall** [comment]
Hi @saraheagle 

The module does not load javascript (Bootstrap) is the template that should do it if you want to open information in a popup window.

Also check for errors in the browser console.

See also: #19 , #28 , #30

**Comment by saraheagle** [comment]
I hadn't got as far as wondering about the popup, I was just looking at the link itself!
I have just turned off the popup and it works now.
Maybe popping a bit of text under the "Article in popup" button to say "This module does not load the modal popup code, you need to make sure your template does that" and turning it off by default would help others?
Thanks very much for your super quick help :)
