### ISSUE TITLE
JB Cookies - adjustments seem to be difficult

### ISSUE THREAD

**Issue by Sandvelder** [JoomBall/JBCookies#34]
Hi
I installed JB Cookies to install on a South African website of an international non-profit. The idea is that it should pop up and give the visitor the legal right to accept or decline. While I adjusted the [Show Decline] button, nothing changed on the front end. I noticed a link to "Learn more" where the visitor can click to get more information on my cookies policy. It is hard coded to [site-name]/#jbcookies. There is no parameter to adjust this or the link to point to an article. So I looked for it and found it in /modules/mod_jbcookies/tmpl/default.php and default_custom.php. I created an article and adjusted the php but to no avail. The default_custom.php changed the link, but clicking on it did not open my article.

**Comment by JoomBall** [comment]
Your questions have already been answered in #28. You have to remove popup window and add item in languages tab.

**Comment by Sandvelder** [comment]
I uninstalled JBCookies and used Engagebox instead.
