### ISSUE TITLE
Error with last release

### ISSUE THREAD

**Issue by micropalla** [JoomBall/JBCookies#7]
0 - syntax error, unexpected $end, expecting TC_DOLLAR_CURLY or TC_QUOTED_STRING or '"' in /home/siti/www.ferrovie.info/ferrovie.info/htdocs/modules/mod_jbcookies/language/it-IT/it-IT.mod_jbcookies.ini on line 71
Non è possibile visualizzare questa pagina, potrebbe essere a causa di:

un bookmark/preferiti scaduto
una ricerca attraverso il motore di ricerca che ha una indicizzazione non aggiornata di questo sito
un indirizzo compilato male
non hai accesso a questa pagina
la risorsa richiesta non esiste.
si è verificato un errore durante l'esecuzione della richiesta.
Prova a visitare una delle seguenti pagine

Home Page
Se persistono delle difficoltà, contatta l'Amministratore di questo sito e riporta l'errore

syntax error, unexpected $end, expecting TC_DOLLAR_CURLY or TC_QUOTED_STRING or '"' in /home/siti/www.ferrovie.info/ferrovie.info/htdocs/modules/mod_jbcookies/language/it-IT/it-IT.mod_jbcookies.ini on line 71

**Comment by micropalla** [comment]
There is a mistake in the last line of the it-IT.mod_jbcookies.ini.
It should be JBVOTE_TITLE="Per favore aiutaci: vota e commenta il nostro modulo nella directory delle estensioni di Joomla, in questo modo potrai aiutarci a sostenere lo sviluppo di questo modulo con nuove modifiche ed aggiornamenti futuri. Grazie mille!."

**Comment by JoomBall** [comment]
Hi @micropalla ,
I just updated this incident, thanks for your input!
