### ISSUE TITLE
jb decline not showing

### ISSUE THREAD

**Issue by Ann-Sophie81** [JoomBall/JBCookies#8]
jb decline not showing after Update to 3.1.1

<script type="text/javascript">
--
  | jQuery(document).ready(function () {
  | function setCookie(c_name,value,exdays)
  | {
  | var exdate=new Date();
  | exdate.setDate(exdate.getDate() + exdays);
  | var c_value=escape(value) + ((exdays==null) ? "" : "; expires="+exdate.toUTCString()) + "; path=/";
  | document.cookie=c_name + "=" + c_value;
  | }
  | jQuery('.jb.decline').click(function(){
  | setCookie("jbcookies","",0);
  | window.location.reload();
  | });
  | });
  | </script>

**Comment by joboca** [comment]
Check the position of the module and delete the browser cookie. Check for possible javascript errors in the console.

**Comment by Ann-Sophie81** [comment]
This part is missing



--
  | <style type="text/css">
  | .jb.decline.link {
  | color: #37a4fc;
  | padding: 0;
  | }
  | </style>
  | 
  | <div class="jb cookie-decline ">
  | <p>
  | Für optimalen Benutzerservice auf dieser Webseite verwenden wir Cookies.		<span class="btn btn-link jb decline link">Cookies löschen</span>
  | </p>
  | </div>
  |

**Comment by Ann-Sophie81** [comment]
### 


--
  | <style type="text/css">
  | .jb.decline.link {
  | color: #37a4fc;
  | padding: 0;
  | }
  | </style>
  | 
  | <div class="jb cookie-decline ">
  | <p>
  | Für optimalen Benutzerservice auf dieser Webseite verwenden wir Cookies.		<span class="btn btn-link jb decline link">Cookies löschen</span>
  | </p>
  | </div>
  |

**Comment by Ann-Sophie81** [comment]
Position is debug. The Cookie accept is showing but not the decline.

No javascript errors in console. 
All Cookies deleted but still the same

example
view-source:https://www.demo-domain.de/joom/ showing decline
view-source:https://neu.brk-gilching.de/ not showing

booth is the same configuration

**Comment by joboca** [comment]
The debug position is not usually visible for modules. Add a position that is visible in the template or modify css for the debug position.

**Comment by Ann-Sophie81** [comment]
It is visible. I see the cookie accept button on debug position but not the cookie delete button...

**Comment by joboca** [comment]
They have nothing to do with one button with another, one appears with javascript and the other needs a template space. Try another position to understand.

**Comment by Ann-Sophie81** [comment]
Yes, but it is working finde on other pages with the same template in debug position. But not on this one

neu.brk-gilching.de here the dicline part is disparing from the code :-(

**Comment by joboca** [comment]
Difficult to help you without access.

Verify comparing websites:

1. Version of everything (Template, module)
2. Revise the parameters of the module (Activate show declining).
3. Remove cache from the module (Advanced tab).

**Comment by Ann-Sophie81** [comment]
I am so sorry, in my template it was removed without telling me.
