### ISSUE TITLE
cookie banner reappears in mobile browser

### ISSUE THREAD

**Issue by francisnadal** [JoomBall/JBCookies#9]
Hi, we have this site https://advocatenkantoor-mattijs.be/ that uses the plugin. On desktop it works fine. But in mobile after clicking accept the cookie banner normally slides down to be hidden. But when navigating to other page in mobile the cookie banner reappears and the accept button cant be clicked. It doesn't go away in mobile browser.

**Comment by joboca** [comment]
I do not have any problem on the mobile. Verify that you have no javascript errors and remove the browser cache.

**Comment by francisnadal** [comment]
Sorry we were able to fix it and discovered a js line where it shows the banner when the js file is loaded. Thank you very much for looking into it.

**Comment by joboca** [comment]
You always have to check javascript errors in the console, it's usually the main problem.
I'm glad you solved it :)

**Comment by francisnadal** [comment]
There wasn't an error in the console but there was a deliberate code where it declares the banner to reappear even after accepting the banner button :) but yeah I''m also relieved it worked out.
